language:
  - node_js
  - ruby
rvm:
  - 1.25.28
ruby:
  - 2.1.2p95
rails:
  - 4.1.5
env:
  - DB=neo4j
node_js:
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
  - bundle exec rake
