language: ruby
rvm:
  - 2.1.5
rails:
  - 4.2.0.beta4
jdk:
  - oraclejdk7
env:
  - DB=neo4j
before_script:
  - gem install rake
  - bundle install --no-deployment
  - bundle update
  - rake neo4j:install[community-2.1.5]
	- rake neo4j:start[community-2.1.5]
