default: &defaults
  twitter:
    key: "vrHp8HSVbfjIboeAf7CsLs4FV"
    secret: "Fc32qocRh1F5SNDCkP9CbazJR9QPEPJ7yPqo56Nx2GTvtmI5rr"
  facebook:
    key: "260971864007757"
    secret: "0c44e3a31c646970c4f28506ed1b03d3"
  linkedin:
    key: "tbd"
    secret: "tbd"
  gplus:
    key: "tbd"
    secret: "tbd"
    scope: "userinfo.email, userinfo.profile"
  github:
    key: "tbd"
    secret: "tbd"
    scope: "user,repo,gist"


development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

